version: '3.8'

services:
  postgres:
    container_name: simplebank_db
    restart: always
    image: postgres:13
    volumes:
      - ./dockerConfig/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql # will setup dev database golang_app for us
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432